package es.jbp.kajtools.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import es.jbp.kajtools.batch.BatchContext;
import es.jbp.kajtools.batch.BatchService;
import es.jbp.kajtools.batch.PersistenceService;
import lombok.Getter;
import org.apache.commons.text.StringEscapeUtils;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.JTextComponent;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.lang.reflect.Method;
import java.util.*;
import java.util.List;
import java.util.stream.Collectors;

public class BatchPanel extends BasePanel {

    @Getter
    private JPanel contentPane;
    private JButton buttonExecute;
    private JButton buttonStop;
    private JTextField searchTextField;
    private JTabbedPane tabbedPane;
    private JPanel tabInfo;
    private InfoTextPane infoTextPane;
    private JButton cleanButton;
    private JButton copyButton;
    private JComboBox<BatchService> comboService;
    private RTextScrollPane paramScrollPane;
    private JPanel tabParam;
    private RSyntaxTextArea paramEditor;

    private BatchContext batchContext;
    private final PersistenceService persistenceService;

    public BatchPanel(List<BatchService> batchServices,
                      PersistenceService persistenceService,
                      UiComponentCreator componentFactory) {
        super(componentFactory);
        this.persistenceService = persistenceService;

        $$$setupUI$$$();
        buttonExecute.addActionListener(e -> start());
        buttonStop.addActionListener(e -> stop());

        copyButton.addActionListener(e -> copyToClipboard());
        cleanButton.addActionListener(e -> cleanEditor());

        batchServices.forEach(s -> comboService.addItem(s));
        comboService.addActionListener(e -> updateParams());

        updateParams();

        super.initialize();
    }

    private void updateParams() {
        var batchService = (BatchService) comboService.getSelectedItem();
        if (batchService == null) {
            return;
        }
        var params = persistenceService.getPropertiesText(batchService.getClass().getName(), batchService.getParameterNames());

        paramEditor.setText(params);
    }

    private void stop() {
        if (batchContext != null) {
            batchContext.stop();
        }
    }

    private void start() {

        var batchService = (BatchService) comboService.getSelectedItem();

        if (batchService == null) {
            return;
        }

        var parameterText = Arrays.stream(paramEditor.getText().split("\n"))
                .sequential()
                .map(StringEscapeUtils::escapeJava)
                .collect(Collectors.joining("\n"));

        var parameters = createVariableMap(parameterText);

        persistenceService.forceProperties(batchService.getClass().getName(), parameters);
        batchContext = batchService.start(parameters, this);
    }

    @Override
    public void update() {
        SwingUtilities.invokeLater(() -> {
            buttonExecute.setEnabled(batchContext == null || !batchContext.isRunning());
            buttonStop.setEnabled(batchContext != null && batchContext.isRunning());
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.add(panel1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        buttonExecute = new JButton();
        buttonExecute.setIcon(new ImageIcon(getClass().getResource("/images/execute.png")));
        buttonExecute.setText("Execute");
        panel2.add(buttonExecute, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        buttonStop = new JButton();
        buttonStop.setEnabled(false);
        buttonStop.setIcon(new ImageIcon(getClass().getResource("/images/stop.png")));
        buttonStop.setText("");
        buttonStop.setToolTipText("Stop");
        panel2.add(buttonStop, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(615, 40), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Action:");
        panel3.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboService = new JComboBox();
        panel3.add(comboService, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel1.add(panel4, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setIcon(new ImageIcon(getClass().getResource("/images/search.png")));
        label2.setText("");
        panel4.add(label2, BorderLayout.WEST);
        searchTextField = new JTextField();
        searchTextField.setText("");
        panel4.add(searchTextField, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel1.add(panel5, new GridConstraints(2, 0, 2, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tabbedPane = new JTabbedPane();
        panel5.add(tabbedPane, BorderLayout.CENTER);
        tabInfo = new JPanel();
        tabInfo.setLayout(new BorderLayout(0, 0));
        tabbedPane.addTab(this.$$$getMessageFromBundle$$$("messages", "tab.info"), tabInfo);
        final JScrollPane scrollPane1 = new JScrollPane();
        tabInfo.add(scrollPane1, BorderLayout.CENTER);
        infoTextPane = new InfoTextPane();
        infoTextPane.setBackground(new Color(-13948117));
        infoTextPane.setCaretColor(new Color(-1));
        infoTextPane.setContentType("text/html");
        infoTextPane.setEditable(false);
        infoTextPane.setEnabled(true);
        Font infoTextPaneFont = this.$$$getFont$$$(null, -1, -1, infoTextPane.getFont());
        if (infoTextPaneFont != null) infoTextPane.setFont(infoTextPaneFont);
        infoTextPane.setForeground(new Color(-1));
        scrollPane1.setViewportView(infoTextPane);
        tabParam = new JPanel();
        tabParam.setLayout(new BorderLayout(0, 0));
        tabbedPane.addTab("Parámetros", tabParam);
        tabParam.add(paramScrollPane, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.add(panel6, BorderLayout.EAST);
        cleanButton = new JButton();
        cleanButton.setIcon(new ImageIcon(getClass().getResource("/images/rubber.png")));
        cleanButton.setText("");
        cleanButton.setToolTipText("Limpiar");
        panel6.add(cleanButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        copyButton = new JButton();
        copyButton.setIcon(new ImageIcon(getClass().getResource("/images/copy.png")));
        copyButton.setText("");
        copyButton.setToolTipText(this.$$$getMessageFromBundle$$$("messages", "tooltip.copy.clipboard"));
        panel6.add(copyButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel6.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel6.add(spacer3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    @Override
    public InfoTextPane getInfoTextPane() {
        return infoTextPane;
    }

    @Override
    public JTextField getSearchTextField() {
        return searchTextField;
    }

    @Override
    public Optional<JTextComponent> getCurrentEditor() {
        int index = tabbedPane.getSelectedIndex();
        if (index == 0) {
            return Optional.of(infoTextPane);
        } else {
            return Optional.of(paramEditor);
        }
    }

    private void createUIComponents() {
        paramEditor = createPropertiesEditor();
        paramScrollPane = componentFactory.createEditorScroll(paramEditor);
    }

}
