package es.jbp.kajtools.ui;

import es.jbp.kajtools.ui.interfaces.DialogueablePanel;
import es.jbp.kajtools.ui.interfaces.SearchablePanel;
import java.awt.BorderLayout;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import lombok.Getter;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;

public class RSyntaxPanel implements DialogueablePanel, SearchablePanel {

  private RTextScrollPane scrollPane;

  private RSyntaxTextArea syntaxTextArea;
  @Getter
  private JPanel mainPanel;
  @Getter
  private JTextField searchTextField;


  public RSyntaxPanel() {
    $$$setupUI$$$();
    enableTextSearch(searchTextField, syntaxTextArea);
  }

  @Override
  public void bindDialog(JDialog dialog) {
  }

  public void setContent(String plainText, String styleKey) {
    syntaxTextArea.setSyntaxEditingStyle(styleKey);
    syntaxTextArea.setText(plainText);
    syntaxTextArea.setCaretPosition(0);
  }

  private void createUIComponents() {
    syntaxTextArea = ComponentFactory.createSyntaxEditor();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
   * code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(0, 0));
    scrollPane = new RTextScrollPane();
    mainPanel.add(scrollPane, BorderLayout.CENTER);
    scrollPane.setViewportView(syntaxTextArea);
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    mainPanel.add(panel1, BorderLayout.SOUTH);
    final JLabel label1 = new JLabel();
    label1.setIcon(new ImageIcon(getClass().getResource("/images/search.png")));
    label1.setText("");
    panel1.add(label1, BorderLayout.WEST);
    searchTextField = new JTextField();
    searchTextField.setText("");
    panel1.add(searchTextField, BorderLayout.CENTER);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

  @Override
  public Optional<JTextComponent> getCurrentEditor() {
    return Optional.of(syntaxTextArea);
  }
}
