package es.jbp.kajtools.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import es.jbp.kajtools.tabla.ModeloTablaGenerico;
import es.jbp.kajtools.tabla.TablaGenerica;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import lombok.Getter;

public class TableSelectorPanel<T> {

  private JTable table;
  @Getter
  private JPanel contentPane;
  private JTextField textFieldFilter;
  private JButton buttonOk;
  private boolean okButtonPressed;

  private final ModeloTablaGenerico<T> tableModel;

  public TableSelectorPanel(
      ModeloTablaGenerico<T> tableModel) {
    this.tableModel = tableModel;

    $$$setupUI$$$();

    textFieldFilter.getDocument().addDocumentListener(new DocumentListener() {
      @Override
      public void insertUpdate(DocumentEvent e) {
        applyFilter();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        applyFilter();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        applyFilter();
      }
    });
  }

  private void applyFilter() {
    String filterText = textFieldFilter.getText();
    tableModel.filtrarPorPredicado(t -> t.toString().contains(filterText));
  }

  public void bindDialog(JDialog dialog) {
    contentPane.getRootPane().setDefaultButton(buttonOk);
    buttonOk.addActionListener(e -> {
      okButtonPressed = true;
      dialog.setVisible(false);
      dialog.dispose();
    });
  }


  private void createUIComponents() {

    TablaGenerica tablaGenerica = new TablaGenerica();
    tablaGenerica.setModel(tableModel);
    table = tablaGenerica;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
   * code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    contentPane = new JPanel();
    contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(8, 8, 8, 8), -1, -1));
    final JScrollPane scrollPane1 = new JScrollPane();
    contentPane.add(scrollPane1,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    scrollPane1.setViewportView(table);
    textFieldFilter = new JTextField();
    contentPane.add(textFieldFilter,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
            GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null,
            0, false));
    buttonOk = new JButton();
    buttonOk.setText("Aceptar");
    contentPane.add(buttonOk, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
        null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPane;
  }

  public T getSelectedItem() {
    if (!okButtonPressed) {
      return null;
    }
    int index = table.getSelectedRow();
    return tableModel.getFila(index);
  }
}
